name: ci bun composite action testing
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: run composite bun action
        id: bun-composite-action
        uses: ./.github/actions/bun-composite-action
        with:
          who-to-greet: 'michal'
      - name: printing out output value
        run: echo ${{ steps.bun-composite-action.outputs.time }}
        