name: First simple pipeline

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  # Name of the job cannot contain spaces.
  first-build-action:
    runs-on: ubuntu-latest
    
    steps:
      - name: first step
        run: echo "This is the first step"
