name: Custom js action workflow
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v
      - name: Run custom js action
        id: js-action
        uses: ./.github/actions/simple-js-action
        with:
          custom-name: 'first input value passed'
      - name: Output value from js action
        run: |
          echo "Output value: ${{ steps.js-action.outputs.js-output }}"
