name: Matrix jobs demo
on:
  workflow_dispatch:

jobs:
  build:
    # By default, if one of the matrix jobs fails, the rest that didn't have the chance
    # to execute are skipped. This ensures that all are executed.
    continue-on-error: true
    strategy:
      matrix:
        # The 'environment' below, in the matrix, is just an arbitrary key in this example.
        # It has nothing to do with deployments to environments.
        environment: [dev, test, prod]
        # include and exclude are reserved words
        include:
          - environment: staging
            operating-system: linux
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: |
          echo "This is the first step for: ${{ matrix.environment }}"
          echo "Operating system ${{ matrix.operating-system }}"
      - name: Second Step
        run: echo "This is the second step. Always the same"
  
  # This doesn't work in this way. Even when the first job has the displayed name
  # as "build (prod)", we cannot reference this name in the next job's 'needs' property.
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: "build (prod)"
  #   steps:
  #     - name: Deploy first step
  #       run: echo "deploying ..."
