name: Matrix jobs demo
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        # environment below is just an arbitrary key in this example.
        # It has nothing to do with deployments to environments.
        environment: [dev, test, prod]
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: |
          echo "This is the first step for: ${{ matrix.environment }}"
      - name: Second Step
        run: echo "This is the second step. Always the same"
  
  # This doesn't work in this way. Even when the first job has the displayed name
  # as "build (prod)", we cannot reference this name in the next job's 'needs' property.
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: "build (prod)"
  #   steps:
  #     - name: Deploy first step
  #       run: echo "deploying ..."
