name: reusable-workflow
on:
  # workflow_call makes it not runnable on its own, but can be run from other workflows.
  workflow_call:
    inputs:
      passed-value:
        description: Pass here value as an input
        required: false
        default: default input value
        type: string # type is mandatory
      environment:
        required: true
        default: dev
        type: string
    secrets:
      super-secret-value:
        description: This is our super secret value passed by the caller
        required: false
      # Refer to the https://github.com/actions/runner/issues/1490 for passing secrets
      SECRET_PASSWORD:
        description: Secret is defined as the environment secret.
        required: true
    outputs:
      reusable-result:
        description: Result value from the reusable workflow
        value: ${{ jobs.deploy.outputs.result }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    # This will ensure that the environment secret will be fetched.
    # But requires "secrets: inherit" to be set by the caller.
    environment: ${{ inputs.environment }}
    outputs:
      result: ${{ steps.output.outputs.set-output }} # 2nd is id of the step, 3rd its outputs, 4th our output value
    steps:
      - name: First step in reusable workflow
        run: echo "Starting the first step"
      - name: Printing input value
        run: echo ${{ inputs.passed-value }}
      - name: Printing the secret
        run: echo ${{ secrets.SECRET_PASSWORD }}
      - name: Set output
        id: output # Step has to have id to reference it in the outputs of this job.
        run: echo "set-output=ok" >> $GITHUB_OUTPUT
